# Generated by Django 3.0.8 on 2020-07-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del menu')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del restaurante')),
                ('image', models.ImageField(upload_to='Restaurant/', verbose_name='Imagen del restaurante')),
                ('address', models.CharField(max_length=50, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefono del restaurant')),
                ('qualification', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del tipo de menu')),
                ('restaurant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Precio')),
                ('image', models.ImageField(upload_to='Product/', verbose_name='Imagen del producto')),
                ('discount', models.FloatField(null=True)),
                ('description', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='type_menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.TypeMenu'),
        ),
    ]
